# -*- coding: utf-8 -*-
"""Программная инженерия Homework №1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18aCRayq-RP0lEV_TQXvhrXVF7yJ5LHdj
"""

!pip install transformers

from transformers import pipeline

unmasker = pipeline('fill-mask', model='bert-base-multilingual-cased')
unmasker("I have never seen him before. Most probably, he is [MASK] student.")